---
title: "Daily Dietary Intake"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r data, include=FALSE, echo=FALSE}

# load packages
source("code/load_packages.R")

# get data
source("code/get_cleaned_data.R")

theme_set(theme_bw())
pal = "Set1"
scale_colour_discrete <-  function(palname=pal, ...){
  scale_colour_brewer(palette=palname, ...)
}
scale_fill_discrete <-  function(palname=pal, ...){
  scale_fill_brewer(palette=palname, ...)
}

knitr::opts_chunk$set(out.width = "200%")

```


# Data prep

Need to do some extra recoding to make things easier

```{r}

diet.data <- read_xlsx("data/analysis-data/Dietary_Variables.xlsx")
diet.data <- diet.data %>%
  mutate(SubjectID = as.numeric(substr(SubjectID, 7,11)),
         Week = RecallNo)



```


# Make Dietary Figures

## Food Groups

```{r}

food_var <- colnames(diet.data)[4:12]

food_data <- as_tibble(diet.data[, c("SubjectID", "Week", food_var)])
# need to fill in "missing" data
MIS <- tidyr::expand(food_data, SubjectID, Week)

food_data <- full_join(food_data, MIS)
id <- paste0("id.", food_data$SubjectID,".wk.",food_data$Week)

food_data$MISSING <- apply(food_data, 1,
                           FUN = function(x){ sum(is.na(x)) })

food_data <- data.frame(t(food_data[,-c(1:2)]))
colnames(food_data) <- id
rownames(food_data) <- c(food_var, "MISSING")

food_data <- apply(food_data, c(1,2), FUN=function(x){ifelse(is.na(x), 0, x)})
food_data <- data.frame(food_data)
# Compute relative abundance
food_data <- sweep(food_data, 2, colSums(food_data), '/')

# sort by highest average relative abundance
food_data <- food_data[order(rowMeans(food_data), decreasing = F),]
rn <- rownames(food_data)
food_data <- food_data[ rn[c(1:8, 10, 9)], ]

# make food ordering factor
food_ord_factor <- as.character(rownames(food_data))

plot3 <- as.data.frame(t(food_data))
plot3 <- rownames_to_column(plot3, var = "SampleID")
plot3 <- reshape2::melt(plot3, id = "SampleID", variable.name = "Food")

# combine all "<x% abundance" foods into one for plotting
#plot3 <- plot3 %>% group_by(SampleID, Food) %>% dplyr::summarise(newvalue = sum(value))

# Extract ids and weeks
#plot3$SubjectID <- str_sub(plot3$SampleID, 4,7)
plot3$SubjectID <- as.numeric(as.factor(str_sub(plot3$SampleID, 4,7)))

plot3$Week <- as.numeric(str_sub(plot3$SampleID, 12, 13))
# recode FOOD
plot3$Food <- as.factor(plot3$Food)
plot3$Food <- factor(plot3$Food, levels = rev(food_ord_factor))
# set seed to get nice colors
set.seed(3)

# get right number of colors for plotting
no_cols <- length(unique(plot3$Food))

## Some Colors
colors_food <- rev(c("#fe9700",
                     "#858c69",
                     "#c91acb",
                     "#737373",
                     "#d43f1f",
                     "#a8863a",
                     "#5dd047",
                     "#00a2f2",
                     "#ffff59",
                     "#662a00",
                     "grey90"))



# make the plot
food_plot<-ggplot(data = plot3, aes(x=Week, y = value, fill=Food)) +
  geom_area(stat = "identity") +
  facet_grid(.~SubjectID, scales = "free") +
  scale_fill_manual(values = colors_food) +
  lims(x=c(0.99, 4.01))+
  theme_classic() +
  theme(strip.text.x = element_text(angle = 0, size = 6, face = "italic"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.title = element_text(size = 10),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        strip.text = element_text(size=10),
        strip.background = element_rect(color = "grey"),
        legend.position = "right",
        legend.text = element_text(size = 7),
        legend.title = element_blank(),
        panel.spacing.x=unit(0.001, "lines")) +
  guides(fill = guide_legend(reverse = TRUE,
                             keywidth = 0.5,
                             keyheight = 0.5,
                             ncol = 1)) +
  #nrow = 5)) + # for full page figure
  #nrow = 1)) + # for slide figure
  ylab("Relative Abundance")
food_plot



```


## Nutrients

```{r}

# Dietary Nurtrients


food_var <- colnames(diet.data)[14:54]


food_data <- as_tibble(diet.data[, c("SubjectID", "Week", food_var)])
# need to fill in "missing" data
MIS <- tidyr::expand(food_data, SubjectID, Week)

food_data <- full_join(food_data, MIS)
id <- paste0("id.", food_data$SubjectID,".wk.",food_data$Week)

food_data$MISSING <- apply(food_data, 1,
                           FUN = function(x){ sum(is.na(x)) })

food_data <- data.frame(t(food_data[,-c(1:2)]))
colnames(food_data) <- id
rownames(food_data) <- c(food_var, "MISSING")

food_data <- apply(food_data, c(1,2), FUN=function(x){ifelse(is.na(x), 0, x)})
food_data <- data.frame(food_data)
# Compute relative abundance
food_data <- sweep(food_data, 2, colSums(food_data), '/')

# sort by highest average relative abundance
food_data <- food_data[order(rowMeans(food_data), decreasing = F),]
rn <- rownames(food_data)
#food_data <- food_data[ rn[c(1:8, 10, 9)], ]

# make food ordering factor
food_ord_factor <- as.character(rownames(food_data))

plot3 <- as.data.frame(t(food_data))
plot3 <- rownames_to_column(plot3, var = "SampleID")
plot3 <- reshape2::melt(plot3, id = "SampleID", variable.name = "Food")

# Extract ids and weeks
plot3$SubjectID <- str_sub(plot3$SampleID, 4,7)
plot3$Week <- as.numeric(str_sub(plot3$SampleID, 12, 13))
# recode FOOD
plot3$Food <- as.factor(plot3$Food)
plot3$Food <- factor(plot3$Food, levels = rev(food_ord_factor))
# set seed to get nice colors
set.seed(3)

# get right number of colors for plotting
no_cols <- length(unique(plot3$Food))

## Some Colors
colors_food <- c("grey90", "#7f6600", "#cc00ff", "#7f5940", "#cc5200", "#00d957", "#40202d", "#e60099", "#006fa6", "#f29d3d", "#300059", "#566573", "#336655", "#83008c", "#d9a3aa", "#400009", "#0020f2", "#a3d936", "#8091ff", "#fbffbf", "#00ffcc", "#8c4f46", "#354020", "#39c3e6", "#333a66", "#ff0000", "#6a8040", "#a6538a", "#402910", "#730f00", "#0a4d00", "#ffe1bf", "#a3d9b1", "#003033", "#f29979", "#00b3a7", "#cbace6", "#bfd9ff", "#bf0000", "#293aa6", "#594943", "#e5c339")



# make the plot
nutr_plot<-ggplot(data = plot3, aes(x=Week, y = value, fill=Food)) +
  geom_area(stat = "identity") +
  facet_grid(.~SubjectID, scales = "free") +
  scale_fill_manual(values = colors_food) +
  lims(x=c(0.99, 4.01))+
  theme_classic() +
  theme(strip.text.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.title = element_text(size = 10),
        plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        strip.background = element_blank(),
        legend.position = "right",
        legend.text = element_text(size = 7),
        legend.title = element_blank(),
        panel.spacing.x=unit(0.01, "lines")) +
  guides(fill = guide_legend(reverse = TRUE,
                             keywidth = 0.5,
                             keyheight = 0.5,
                             ncol = 1)) +
  #nrow = 5)) + # for full page figure
  #nrow = 1)) + # for slide figure
  ylab("Relative Abundance")
nutr_plot



```


## Saving plot

```{r}

##### MAKE THE ACTUAL FIGURE ###########
# combine into one big plot

#food_plot_leg <- get_legend(food_plot)
#nutr_plot_leg <- get_legend(nutr_plot)

# and replot suppressing the legend
food_plot_1 <- food_plot #+ theme(legend.position='none')
nutr_plot_1 <- nutr_plot #+ theme(legend.position='none')

p <- food_plot_1 + nutr_plot_1 + plot_layout(ncol=1)

p
#ggsave("figure1.pdf", p, units="in", width=7.9,height=4.5)




#bigplotlegend <- plot_grid(food_plot_leg, nutr_plot_leg, nrow =1, align = "h")

#save_plot("figure1_legend.pdf", bigplotlegend, base_width = 13.25, base_height = 5)


```
