---
title: "Relationship between Microbiome and Food"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

This page contains the investigation of the changes over time.

```{r data, include=FALSE, echo=FALSE}

# load packages
source("code/load_packages.R")

# get data
source("code/get_cleaned_data.R")

theme_set(theme_bw())
pal = "Set1"
scale_colour_discrete <-  function(palname=pal, ...){
  scale_colour_brewer(palette=palname, ...)
}
scale_fill_discrete <-  function(palname=pal, ...){
  scale_fill_brewer(palette=palname, ...)
}

knitr::opts_chunk$set(out.width = "225%")

```

# Phylum Level Microbiome and Food

Get the phylum level data

```{r}

data.phylum <-get_combined_data(mydata=microbiome_data,
                                taxa.level="Phylum")

#phylum 
bugs <- data.phylum$bug.list
bugs
```

## Correlation between Phylum and HEI scores

### Start of Study (Baseline, Week 1)

```{r}

subdat <- filter(data.phylum$full_data, Week == "1")

ggplot(subdat, aes(x=Abundance, y=HEI_Total,
                   color=Intervention))+
  geom_point(size=3)+
  facet_wrap(.~Bug, scales = "free")+
  theme(axis.text.x = element_text(angle=20, size=7, vjust=0.1))

```

### 1st follw-up (Week 4)

```{r}

subdat <- filter(data.phylum$full_data, Week == "4")

ggplot(subdat, aes(x=Abundance, y=HEI_Total,
                   color=Intervention))+
  geom_point(size=3)+
  facet_wrap(.~Bug, scales = "free")+
  theme(axis.text.x = element_text(angle=20, size=7, vjust=0.1))

```


### Second follw-up (Week 8)

```{r}

subdat <- filter(data.phylum$full_data, Week == "8")

ggplot(subdat, aes(x=Abundance, y=HEI_Total,
                   color=Intervention))+
  geom_point(size=3)+
  facet_wrap(.~Bug, scales = "free")+
  theme(axis.text.x = element_text(angle=20, size=7, vjust=0.1))

```


### Third follw-up (Week 12)

```{r}

subdat <- filter(data.phylum$full_data, Week == "12")

ggplot(subdat, aes(x=Abundance, y=HEI_Total,
                   color=Intervention))+
  geom_point(size=3)+
  facet_wrap(.~Bug, scales = "free")+
  theme(axis.text.x = element_text(angle=20, size=7, vjust=0.1))

```

